language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh -c "phpize && ./configure && make"

script:
  - sh -c "TEST_PHP_ARGS="-qTEST_PHP_ARGS='-q' make test | tee result.txt"
  - sh test-report.sh

notifications:
  email:
    - kaczanowski.mateusz@gmail.com
